package main

import (
    "flag"
    "fmt"
    "net/http"
    "os"
    "strconv"
    )


func main () {
    var port string
    p := *flag.Int ("port", 0, "listening port")
    if p == 0 {
        port = os.Getenv ("PORT")
        if len (port) < 1 {
            port = "8080"
        }
    } else {
        port = strconv.FormatInt (int64 (p), 10)
    }
    http.HandleFunc ("/",           Hello)
    http.HandleFunc ("/ddgi/",      DDGTestImage)
    http.HandleFunc ("/google/",    Google)
    http.HandleFunc ("/pkmn/",      PokemonBig)
    http.HandleFunc ("/pkmn/smol/", PokemonSmol)
    fmt.Println ("Listening...")
    err := http.ListenAndServe (":" + port, nil)
    if err != nil {
        panic (err)
    }
}

func Hello (w http.ResponseWriter, r *http.Request) {
    fmt.Fprintln (w, "Hello, world")
}

func DDGTestImage (w http.ResponseWriter, r *http.Request) {
    http.Redirect (w, r, "https://duckduckgo.com/assets/logo_icon128.v101.png", http.StatusMovedPermanently)
}

func Google (w http.ResponseWriter, r *http.Request) {
    http.Redirect (w, r, "https://google.com", http.StatusMovedPermanently)
}

func Obfuscation (w http.ResponseWriter, r *http.Request) {
    http.Redirect (w, r, "https://google.com", http.StatusMovedPermanently)
}

func PokemonBig (w http.ResponseWriter, r *http.Request) {
    num := r.URL.Path [len ("/pkmn/"):]
    idx, err := strconv.ParseInt (num, 0, 64)
    if err != nil || idx < 1 || idx >= int64 (len (PkmnSmol)) {
        fmt.Fprintf (w, "404")
        return
    }
    var url string
    if idx < int64 (len (Pkmn)) && len (Pkmn [idx]) > 0 {
        url  = "https://cdn.bulbagarden.net/upload/"
        url += Pkmn [idx]
        url += ".png"
    } else {
        url = PkmnSmolURL (idx)
    }
    http.Redirect (w, r, url, http.StatusMovedPermanently)
}

func PokemonSmol (w http.ResponseWriter, r *http.Request) {
    num := r.URL.Path [len ("/pkmn/smol/"):]
    idx, err := strconv.ParseInt (num, 0, 64)
    if err != nil || idx < 1 || idx >= int64 (len (PkmnSmol)) {
        fmt.Fprintf (w, "404")
        return
    }
    url := PkmnSmolURL (idx)
    http.Redirect (w, r, url, http.StatusMovedPermanently)
}

func PkmnSmolURL (idx int64) string {
    s   := PkmnSmol [idx]
    url := "https://img.pokemondb.net/sprites/"
    switch s.Algo {
    case 0: url += "omega-ruby-alpha-sapphire"
    case 1: url += "sun-moon"
    }
    url += "/dex/normal/"
    url += s.Name
    url += ".png"
    return url
}

var Pkmn = []string {
    "",
    "2/21/001Bulbasaur",
}

type PkmnSmolType struct {
    Algo int
    Name string
}

var PkmnSmol = []PkmnSmolType {
        { 0, ""                    },
        { 0, "bulbasaur"           },
        { 0, "ivysaur"             },
        { 0, "venusaur"            },
        { 0, "charmander"          },
        { 0, "charmeleon"          },
        { 0, "charizard"           },
        { 0, "squirtle"            },
        { 0, "wartortle"           },
        { 0, "blastoise"           },
        { 0, "caterpie"            },
        { 0, "metapod"             },
        { 0, "butterfree"          },
        { 0, "weedle"              },
        { 0, "kakuna"              },
        { 0, "beedrill"            },
        { 0, "pidgey"              },
        { 0, "pidgeotto"           },
        { 0, "pidgeot"             },
        { 0, "rattata"             },
        { 0, "raticate"            },
        { 0, "spearow"             },
        { 0, "fearow"              },
        { 0, "ekans"               },
        { 0, "arbok"               },
        { 0, "pikachu"             },
        { 0, "raichu"              },
        { 0, "sandshrew"           },
        { 0, "sandslash"           },
        { 0, "nidoran-f"           },
        { 0, "nidorina"            },
        { 0, "nidoqueen"           },
        { 0, "nidoran-m"           },
        { 0, "nidorino"            },
        { 0, "nidoking"            },
        { 0, "clefairy"            },
        { 0, "clefable"            },
        { 0, "vulpix"              },
        { 0, "ninetales"           },
        { 0, "jigglypuff"          },
        { 0, "wigglytuff"          },
        { 0, "zubat"               },
        { 0, "golbat"              },
        { 0, "oddish"              },
        { 0, "gloom"               },
        { 0, "vileplume"           },
        { 0, "paras"               },
        { 0, "parasect"            },
        { 0, "venonat"             },
        { 0, "venomoth"            },
        { 0, "diglett"             },
        { 0, "dugtrio"             },
        { 0, "meowth"              },
        { 0, "persian"             },
        { 0, "psyduck"             },
        { 0, "golduck"             },
        { 0, "mankey"              },
        { 0, "primeape"            },
        { 0, "growlithe"           },
        { 0, "arcanine"            },
        { 0, "poliwag"             },
        { 0, "poliwhirl"           },
        { 0, "poliwrath"           },
        { 0, "abra"                },
        { 0, "kadabra"             },
        { 0, "alakazam"            },
        { 0, "machop"              },
        { 0, "machoke"             },
        { 0, "machamp"             },
        { 0, "bellsprout"          },
        { 0, "weepinbell"          },
        { 0, "victreebel"          },
        { 0, "tentacool"           },
        { 0, "tentacruel"          },
        { 0, "geodude"             },
        { 0, "graveler"            },
        { 0, "golem"               },
        { 0, "ponyta"              },
        { 0, "rapidash"            },
        { 0, "slowpoke"            },
        { 0, "slowbro"             },
        { 0, "magnemite"           },
        { 0, "magneton"            },
        { 0, "farfetchd"           },
        { 0, "doduo"               },
        { 0, "dodrio"              },
        { 0, "seel"                },
        { 0, "dewgong"             },
        { 0, "grimer"              },
        { 0, "muk"                 },
        { 0, "shellder"            },
        { 0, "cloyster"            },
        { 0, "gastly"              },
        { 0, "haunter"             },
        { 0, "gengar"              },
        { 0, "onix"                },
        { 0, "drowzee"             },
        { 0, "hypno"               },
        { 0, "krabby"              },
        { 0, "kingler"             },
        { 0, "voltorb"             },
        { 0, "electrode"           },
        { 0, "exeggcute"           },
        { 0, "exeggutor"           },
        { 0, "cubone"              },
        { 0, "marowak"             },
        { 0, "hitmonlee"           },
        { 0, "hitmonchan"          },
        { 0, "lickitung"           },
        { 0, "koffing"             },
        { 0, "weezing"             },
        { 0, "rhyhorn"             },
        { 0, "rhydon"              },
        { 0, "chansey"             },
        { 0, "tangela"             },
        { 0, "kangaskhan"          },
        { 0, "horsea"              },
        { 0, "seadra"              },
        { 0, "goldeen"             },
        { 0, "seaking"             },
        { 0, "staryu"              },
        { 0, "starmie"             },
        { 0, "mr-mime"             },
        { 0, "scyther"             },
        { 0, "jynx"                },
        { 0, "electabuzz"          },
        { 0, "magmar"              },
        { 0, "pinsir"              },
        { 0, "tauros"              },
        { 0, "magikarp"            },
        { 0, "gyarados"            },
        { 0, "lapras"              },
        { 0, "ditto"               },
        { 0, "eevee"               },
        { 0, "vaporeon"            },
        { 0, "jolteon"             },
        { 0, "flareon"             },
        { 0, "porygon"             },
        { 0, "omanyte"             },
        { 0, "omastar"             },
        { 0, "kabuto"              },
        { 0, "kabutops"            },
        { 0, "aerodactyl"          },
        { 0, "snorlax"             },
        { 0, "articuno"            },
        { 0, "zapdos"              },
        { 0, "moltres"             },
        { 0, "dratini"             },
        { 0, "dragonair"           },
        { 0, "dragonite"           },
        { 0, "mewtwo"              },
        { 0, "mew"                 },
        { 0, "chikorita"           },
        { 0, "bayleef"             },
        { 0, "meganium"            },
        { 0, "cyndaquil"           },
        { 0, "quilava"             },
        { 0, "typhlosion"          },
        { 0, "totodile"            },
        { 0, "croconaw"            },
        { 0, "feraligatr"          },
        { 0, "sentret"             },
        { 0, "furret"              },
        { 0, "hoothoot"            },
        { 0, "noctowl"             },
        { 0, "ledyba"              },
        { 0, "ledian"              },
        { 0, "spinarak"            },
        { 0, "ariados"             },
        { 0, "crobat"              },
        { 0, "chinchou"            },
        { 0, "lanturn"             },
        { 0, "pichu"               },
        { 0, "cleffa"              },
        { 0, "igglybuff"           },
        { 0, "togepi"              },
        { 0, "togetic"             },
        { 0, "natu"                },
        { 0, "xatu"                },
        { 0, "mareep"              },
        { 0, "flaaffy"             },
        { 0, "ampharos"            },
        { 0, "bellossom"           },
        { 0, "marill"              },
        { 0, "azumarill"           },
        { 0, "sudowoodo"           },
        { 0, "politoed"            },
        { 0, "hoppip"              },
        { 0, "skiploom"            },
        { 0, "jumpluff"            },
        { 0, "aipom"               },
        { 0, "sunkern"             },
        { 0, "sunflora"            },
        { 0, "yanma"               },
        { 0, "wooper"              },
        { 0, "quagsire"            },
        { 0, "espeon"              },
        { 0, "umbreon"             },
        { 0, "murkrow"             },
        { 0, "slowking"            },
        { 0, "misdreavus"          },
        { 0, "unown"               },
        { 0, "wobbuffet"           },
        { 0, "girafarig"           },
        { 0, "pineco"              },
        { 0, "forretress"          },
        { 0, "dunsparce"           },
        { 0, "gligar"              },
        { 0, "steelix"             },
        { 0, "snubbull"            },
        { 0, "granbull"            },
        { 0, "qwilfish"            },
        { 0, "scizor"              },
        { 0, "shuckle"             },
        { 0, "heracross"           },
        { 0, "sneasel"             },
        { 0, "teddiursa"           },
        { 0, "ursaring"            },
        { 0, "slugma"              },
        { 0, "magcargo"            },
        { 0, "swinub"              },
        { 0, "piloswine"           },
        { 0, "corsola"             },
        { 0, "remoraid"            },
        { 0, "octillery"           },
        { 0, "delibird"            },
        { 0, "mantine"             },
        { 0, "skarmory"            },
        { 0, "houndour"            },
        { 0, "houndoom"            },
        { 0, "kingdra"             },
        { 0, "phanpy"              },
        { 0, "donphan"             },
        { 0, "porygon2"            },
        { 0, "stantler"            },
        { 0, "smeargle"            },
        { 0, "tyrogue"             },
        { 0, "hitmontop"           },
        { 0, "smoochum"            },
        { 0, "elekid"              },
        { 0, "magby"               },
        { 0, "miltank"             },
        { 0, "blissey"             },
        { 0, "raikou"              },
        { 0, "entei"               },
        { 0, "suicune"             },
        { 0, "larvitar"            },
        { 0, "pupitar"             },
        { 0, "tyranitar"           },
        { 0, "lugia"               },
        { 0, "ho-oh"               },
        { 0, "celebi"              },
        { 0, "treecko"             },
        { 0, "grovyle"             },
        { 0, "sceptile"            },
        { 0, "torchic"             },
        { 0, "combusken"           },
        { 0, "blaziken"            },
        { 0, "mudkip"              },
        { 0, "marshtomp"           },
        { 0, "swampert"            },
        { 0, "poochyena"           },
        { 0, "mightyena"           },
        { 0, "zigzagoon"           },
        { 0, "linoone"             },
        { 0, "wurmple"             },
        { 0, "silcoon"             },
        { 0, "beautifly"           },
        { 0, "cascoon"             },
        { 0, "dustox"              },
        { 0, "lotad"               },
        { 0, "lombre"              },
        { 0, "ludicolo"            },
        { 0, "seedot"              },
        { 0, "nuzleaf"             },
        { 0, "shiftry"             },
        { 0, "taillow"             },
        { 0, "swellow"             },
        { 0, "wingull"             },
        { 0, "pelipper"            },
        { 0, "ralts"               },
        { 0, "kirlia"              },
        { 0, "gardevoir"           },
        { 0, "surskit"             },
        { 0, "masquerain"          },
        { 0, "shroomish"           },
        { 0, "breloom"             },
        { 0, "slakoth"             },
        { 0, "vigoroth"            },
        { 0, "slaking"             },
        { 0, "nincada"             },
        { 0, "ninjask"             },
        { 0, "shedinja"            },
        { 0, "whismur"             },
        { 0, "loudred"             },
        { 0, "exploud"             },
        { 0, "makuhita"            },
        { 0, "hariyama"            },
        { 0, "azurill"             },
        { 0, "nosepass"            },
        { 0, "skitty"              },
        { 0, "delcatty"            },
        { 0, "sableye"             },
        { 0, "mawile"              },
        { 0, "aron"                },
        { 0, "lairon"              },
        { 0, "aggron"              },
        { 0, "meditite"            },
        { 0, "medicham"            },
        { 0, "electrike"           },
        { 0, "manectric"           },
        { 0, "plusle"              },
        { 0, "minun"               },
        { 0, "volbeat"             },
        { 0, "illumise"            },
        { 0, "roselia"             },
        { 0, "gulpin"              },
        { 0, "swalot"              },
        { 0, "carvanha"            },
        { 0, "sharpedo"            },
        { 0, "wailmer"             },
        { 0, "wailord"             },
        { 0, "numel"               },
        { 0, "camerupt"            },
        { 0, "torkoal"             },
        { 0, "spoink"              },
        { 0, "grumpig"             },
        { 0, "spinda"              },
        { 0, "trapinch"            },
        { 0, "vibrava"             },
        { 0, "flygon"              },
        { 0, "cacnea"              },
        { 0, "cacturne"            },
        { 0, "swablu"              },
        { 0, "altaria"             },
        { 0, "zangoose"            },
        { 0, "seviper"             },
        { 0, "lunatone"            },
        { 0, "solrock"             },
        { 0, "barboach"            },
        { 0, "whiscash"            },
        { 0, "corphish"            },
        { 0, "crawdaunt"           },
        { 0, "baltoy"              },
        { 0, "claydol"             },
        { 0, "lileep"              },
        { 0, "cradily"             },
        { 0, "anorith"             },
        { 0, "armaldo"             },
        { 0, "feebas"              },
        { 0, "milotic"             },
        { 0, "castform"            },
        { 0, "kecleon"             },
        { 0, "shuppet"             },
        { 0, "banette"             },
        { 0, "duskull"             },
        { 0, "dusclops"            },
        { 0, "tropius"             },
        { 0, "chimecho"            },
        { 0, "absol"               },
        { 0, "wynaut"              },
        { 0, "snorunt"             },
        { 0, "glalie"              },
        { 0, "spheal"              },
        { 0, "sealeo"              },
        { 0, "walrein"             },
        { 0, "clamperl"            },
        { 0, "huntail"             },
        { 0, "gorebyss"            },
        { 0, "relicanth"           },
        { 0, "luvdisc"             },
        { 0, "bagon"               },
        { 0, "shelgon"             },
        { 0, "salamence"           },
        { 0, "beldum"              },
        { 0, "metang"              },
        { 0, "metagross"           },
        { 0, "regirock"            },
        { 0, "regice"              },
        { 0, "registeel"           },
        { 0, "latias"              },
        { 0, "latios"              },
        { 0, "kyogre"              },
        { 0, "groudon"             },
        { 0, "rayquaza"            },
        { 0, "jirachi"             },
        { 0, "deoxys-normal"       },
        { 0, "turtwig"             },
        { 0, "grotle"              },
        { 0, "torterra"            },
        { 0, "chimchar"            },
        { 0, "monferno"            },
        { 0, "infernape"           },
        { 0, "piplup"              },
        { 0, "prinplup"            },
        { 0, "empoleon"            },
        { 0, "starly"              },
        { 0, "staravia"            },
        { 0, "staraptor"           },
        { 0, "bidoof"              },
        { 0, "bibarel"             },
        { 0, "kricketot"           },
        { 0, "kricketune"          },
        { 0, "shinx"               },
        { 0, "luxio"               },
        { 0, "luxray"              },
        { 0, "budew"               },
        { 0, "roserade"            },
        { 0, "cranidos"            },
        { 0, "rampardos"           },
        { 0, "shieldon"            },
        { 0, "bastiodon"           },
        { 0, "burmy"               },
        { 0, "wormadam-plant"      },
        { 0, "mothim"              },
        { 0, "combee"              },
        { 0, "vespiquen"           },
        { 0, "pachirisu"           },
        { 0, "buizel"              },
        { 0, "floatzel"            },
        { 0, "cherubi"             },
        { 0, "cherrim"             },
        { 0, "shellos"             },
        { 0, "gastrodon"           },
        { 0, "ambipom"             },
        { 0, "drifloon"            },
        { 0, "drifblim"            },
        { 0, "buneary"             },
        { 0, "lopunny"             },
        { 0, "mismagius"           },
        { 0, "honchkrow"           },
        { 0, "glameow"             },
        { 0, "purugly"             },
        { 0, "chingling"           },
        { 0, "stunky"              },
        { 0, "skuntank"            },
        { 0, "bronzor"             },
        { 0, "bronzong"            },
        { 0, "bonsly"              },
        { 0, "mime-jr"             },
        { 0, "happiny"             },
        { 0, "chatot"              },
        { 0, "spiritomb"           },
        { 0, "gible"               },
        { 0, "gabite"              },
        { 0, "garchomp"            },
        { 0, "munchlax"            },
        { 0, "riolu"               },
        { 0, "lucario"             },
        { 0, "hippopotas"          },
        { 0, "hippowdon"           },
        { 0, "skorupi"             },
        { 0, "drapion"             },
        { 0, "croagunk"            },
        { 0, "toxicroak"           },
        { 0, "carnivine"           },
        { 0, "finneon"             },
        { 0, "lumineon"            },
        { 0, "mantyke"             },
        { 0, "snover"              },
        { 0, "abomasnow"           },
        { 0, "weavile"             },
        { 0, "magnezone"           },
        { 0, "lickilicky"          },
        { 0, "rhyperior"           },
        { 0, "tangrowth"           },
        { 0, "electivire"          },
        { 0, "magmortar"           },
        { 0, "togekiss"            },
        { 0, "yanmega"             },
        { 0, "leafeon"             },
        { 0, "glaceon"             },
        { 0, "gliscor"             },
        { 0, "mamoswine"           },
        { 0, "porygon-z"           },
        { 0, "gallade"             },
        { 0, "probopass"           },
        { 0, "dusknoir"            },
        { 0, "froslass"            },
        { 0, "rotom"               },
        { 0, "uxie"                },
        { 0, "mesprit"             },
        { 0, "azelf"               },
        { 0, "dialga"              },
        { 0, "palkia"              },
        { 0, "heatran"             },
        { 0, "regigigas"           },
        { 0, "giratina-altered"    },
        { 0, "cresselia"           },
        { 0, "phione"              },
        { 0, "manaphy"             },
        { 0, "darkrai"             },
        { 0, "shaymin-land"        },
        { 0, "arceus"              },
        { 0, "victini"             },
        { 0, "snivy"               },
        { 0, "servine"             },
        { 0, "serperior"           },
        { 0, "tepig"               },
        { 0, "pignite"             },
        { 0, "emboar"              },
        { 0, "oshawott"            },
        { 0, "dewott"              },
        { 0, "samurott"            },
        { 0, "patrat"              },
        { 0, "watchog"             },
        { 0, "lillipup"            },
        { 0, "herdier"             },
        { 0, "stoutland"           },
        { 0, "purrloin"            },
        { 0, "liepard"             },
        { 0, "pansage"             },
        { 0, "simisage"            },
        { 0, "pansear"             },
        { 0, "simisear"            },
        { 0, "panpour"             },
        { 0, "simipour"            },
        { 0, "munna"               },
        { 0, "musharna"            },
        { 0, "pidove"              },
        { 0, "tranquill"           },
        { 0, "unfezant"            },
        { 0, "blitzle"             },
        { 0, "zebstrika"           },
        { 0, "roggenrola"          },
        { 0, "boldore"             },
        { 0, "gigalith"            },
        { 0, "woobat"              },
        { 0, "swoobat"             },
        { 0, "drilbur"             },
        { 0, "excadrill"           },
        { 0, "audino"              },
        { 0, "timburr"             },
        { 0, "gurdurr"             },
        { 0, "conkeldurr"          },
        { 0, "tympole"             },
        { 0, "palpitoad"           },
        { 0, "seismitoad"          },
        { 0, "throh"               },
        { 0, "sawk"                },
        { 0, "sewaddle"            },
        { 0, "swadloon"            },
        { 0, "leavanny"            },
        { 0, "venipede"            },
        { 0, "whirlipede"          },
        { 0, "scolipede"           },
        { 0, "cottonee"            },
        { 0, "whimsicott"          },
        { 0, "petilil"             },
        { 0, "lilligant"           },
        { 0, "basculin-red"        },
        { 0, "sandile"             },
        { 0, "krokorok"            },
        { 0, "krookodile"          },
        { 0, "darumaka"            },
        { 0, "darmanitan-standard" },
        { 0, "maractus"            },
        { 0, "dwebble"             },
        { 0, "crustle"             },
        { 0, "scraggy"             },
        { 0, "scrafty"             },
        { 0, "sigilyph"            },
        { 0, "yamask"              },
        { 0, "cofagrigus"          },
        { 0, "tirtouga"            },
        { 0, "carracosta"          },
        { 0, "archen"              },
        { 0, "archeops"            },
        { 0, "trubbish"            },
        { 0, "garbodor"            },
        { 0, "zorua"               },
        { 0, "zoroark"             },
        { 0, "minccino"            },
        { 0, "cinccino"            },
        { 0, "gothita"             },
        { 0, "gothorita"           },
        { 0, "gothitelle"          },
        { 0, "solosis"             },
        { 0, "duosion"             },
        { 0, "reuniclus"           },
        { 0, "ducklett"            },
        { 0, "swanna"              },
        { 0, "vanillite"           },
        { 0, "vanillish"           },
        { 0, "vanilluxe"           },
        { 0, "deerling"            },
        { 0, "sawsbuck"            },
        { 0, "emolga"              },
        { 0, "karrablast"          },
        { 0, "escavalier"          },
        { 0, "foongus"             },
        { 0, "amoonguss"           },
        { 0, "frillish"            },
        { 0, "jellicent"           },
        { 0, "alomomola"           },
        { 0, "joltik"              },
        { 0, "galvantula"          },
        { 0, "ferroseed"           },
        { 0, "ferrothorn"          },
        { 0, "klink"               },
        { 0, "klang"               },
        { 0, "klinklang"           },
        { 0, "tynamo"              },
        { 0, "eelektrik"           },
        { 0, "eelektross"          },
        { 0, "elgyem"              },
        { 0, "beheeyem"            },
        { 0, "litwick"             },
        { 0, "lampent"             },
        { 0, "chandelure"          },
        { 0, "axew"                },
        { 0, "fraxure"             },
        { 0, "haxorus"             },
        { 0, "cubchoo"             },
        { 0, "beartic"             },
        { 0, "cryogonal"           },
        { 0, "shelmet"             },
        { 0, "accelgor"            },
        { 0, "stunfisk"            },
        { 0, "mienfoo"             },
        { 0, "mienshao"            },
        { 0, "druddigon"           },
        { 0, "golett"              },
        { 0, "golurk"              },
        { 0, "pawniard"            },
        { 0, "bisharp"             },
        { 0, "bouffalant"          },
        { 0, "rufflet"             },
        { 0, "braviary"            },
        { 0, "vullaby"             },
        { 0, "mandibuzz"           },
        { 0, "heatmor"             },
        { 0, "durant"              },
        { 0, "deino"               },
        { 0, "zweilous"            },
        { 0, "hydreigon"           },
        { 0, "larvesta"            },
        { 0, "volcarona"           },
        { 0, "cobalion"            },
        { 0, "terrakion"           },
        { 0, "virizion"            },
        { 0, "tornadus-incarnate"  },
        { 0, "thundurus-incarnate" },
        { 0, "reshiram"            },
        { 0, "zekrom"              },
        { 0, "landorus-incarnate"  },
        { 0, "kyurem"              },
        { 0, "keldeo-ordinary"     },
        { 0, "meloetta-aria"       },
        { 0, "genesect"            },
        { 0, "chespin"             },
        { 0, "quilladin"           },
        { 0, "chesnaught"          },
        { 0, "fennekin"            },
        { 0, "braixen"             },
        { 0, "delphox"             },
        { 0, "froakie"             },
        { 0, "frogadier"           },
        { 0, "greninja"            },
        { 0, "bunnelby"            },
        { 0, "diggersby"           },
        { 0, "fletchling"          },
        { 0, "fletchinder"         },
        { 0, "talonflame"          },
        { 0, "scatterbug"          },
        { 0, "spewpa"              },
        { 0, "vivillon"            },
        { 0, "litleo"              },
        { 0, "pyroar"              },
        { 0, "flabebe"             },
        { 0, "floette"             },
        { 0, "florges"             },
        { 0, "skiddo"              },
        { 0, "gogoat"              },
        { 0, "pancham"             },
        { 0, "pangoro"             },
        { 0, "furfrou"             },
        { 0, "espurr"              },
        { 0, "meowstic-male"       },
        { 0, "honedge"             },
        { 0, "doublade"            },
        { 0, "aegislash-shield"    },
        { 0, "spritzee"            },
        { 0, "aromatisse"          },
        { 0, "swirlix"             },
        { 0, "slurpuff"            },
        { 0, "inkay"               },
        { 0, "malamar"             },
        { 0, "binacle"             },
        { 0, "barbaracle"          },
        { 0, "skrelp"              },
        { 0, "dragalge"            },
        { 0, "clauncher"           },
        { 0, "clawitzer"           },
        { 0, "helioptile"          },
        { 0, "heliolisk"           },
        { 0, "tyrunt"              },
        { 0, "tyrantrum"           },
        { 0, "amaura"              },
        { 0, "aurorus"             },
        { 0, "sylveon"             },
        { 0, "hawlucha"            },
        { 0, "dedenne"             },
        { 0, "carbink"             },
        { 0, "goomy"               },
        { 0, "sliggoo"             },
        { 0, "goodra"              },
        { 0, "klefki"              },
        { 0, "phantump"            },
        { 0, "trevenant"           },
        { 0, "pumpkaboo-average"   },
        { 0, "gourgeist-average"   },
        { 0, "bergmite"            },
        { 0, "avalugg"             },
        { 0, "noibat"              },
        { 0, "noivern"             },
        { 0, "xerneas"             },
        { 0, "yveltal"             },
        { 0, "zygarde"             },
        { 0, "diancie"             },
        { 0, "hoopa"               },
        { 0, "volcanion"           },
        { 1, "rowlet"              },
        { 1, "dartrix"             },
        { 1, "decidueye"           },
        { 1, "litten"              },
        { 1, "torracat"            },
        { 1, "incineroar"          },
        { 1, "popplio"             },
        { 1, "brionne"             },
        { 1, "primarina"           },
        { 1, "pikipek"             },
        { 1, "trumbeak"            },
        { 1, "toucannon"           },
        { 1, "yungoos"             },
        { 1, "gumshoos"            },
        { 1, "grubbin"             },
        { 1, "charjabug"           },
        { 1, "vikavolt"            },
        { 1, "crabrawler"          },
        { 1, "crabominable"        },
        { 1, "oricorio-baile"      },
        { 1, "cutiefly"            },
        { 1, "ribombee"            },
        { 1, "rockruff"            },
        { 1, "lycanroc-midday"     },
        { 1, "wishiwashi-solo"     },
        { 1, "mareanie"            },
        { 1, "toxapex"             },
        { 1, "mudbray"             },
        { 1, "mudsdale"            },
        { 1, "dewpider"            },
        { 1, "araquanid"           },
        { 1, "fomantis"            },
        { 1, "lurantis"            },
        { 1, "morelull"            },
        { 1, "shiinotic"           },
        { 1, "salandit"            },
        { 1, "salazzle"            },
        { 1, "stufful"             },
        { 1, "bewear"              },
        { 1, "bounsweet"           },
        { 1, "steenee"             },
        { 1, "tsareena"            },
        { 1, "comfey"              },
        { 1, "oranguru"            },
        { 1, "passimian"           },
        { 1, "wimpod"              },
        { 1, "golisopod"           },
        { 1, "sandygast"           },
        { 1, "palossand"           },
        { 1, "pyukumuku"           },
        { 1, "type-null"           },
        { 1, "silvally"            },
        { 1, "minior-meteor"       },
        { 1, "komala"              },
        { 1, "turtonator"          },
        { 1, "togedemaru"          },
        { 1, "mimikyu"             },
        { 1, "bruxish"             },
        { 1, "drampa"              },
        { 1, "dhelmise"            },
        { 1, "jangmo-o"            },
        { 1, "hakamo-o"            },
        { 1, "kommo-o"             },
        { 1, "tapu-koko"           },
        { 1, "tapu-lele"           },
        { 1, "tapu-bulu"           },
        { 1, "tapu-fini"           },
        { 1, "cosmog"              },
        { 1, "cosmoem"             },
        { 1, "solgaleo"            },
        { 1, "lunala"              },
        { 1, "nihilego"            },
        { 1, "buzzwole"            },
        { 1, "pheromosa"           },
        { 1, "xurkitree"           },
        { 1, "celesteela"          },
        { 1, "kartana"             },
        { 1, "guzzlord"            },
        { 1, "necrozma"            },
        { 1, "magearna"            },
        { 1, "marshadow"           },
}
